name: "Test"
on:
  pull_request:
  push:
  schedule:
    - cron:  '31 2 * * *'
jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
    - run:
        nix-build -I nixpkgs=channel:nixos-unstable-small
    - run:
        nix-shell -I nixpkgs=channel:nixos-unstable-small --pure --run "NIX_SSL_CERT_FILE=$NIX_SSL_CERT_FILE go test"
    - run:
        nix run nixpkgs.gox -c gox -os '!windows' .
